// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.windows:
        throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for windows - '
        'you can reconfigure this by running the FlutterFire CLI again.',
        );
  
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHdOvaMGgCc2Ckj9P4RL64Ayl2L40uRw0',
    appId: '1:594960202743:android:8f2240e3af142d2017ccf2',
    messagingSenderId: '594960202743',
    projectId: 'mentalhealth-28368',
    storageBucket: 'mentalhealth-28368.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv3tiasv5qngxq6ZV5ochCqjJSCsZGO4U',
    appId: '1:594960202743:ios:a5eb4dcb5bb8730217ccf2',
    messagingSenderId: '594960202743',
    projectId: 'mentalhealth-28368',
    storageBucket: 'mentalhealth-28368.appspot.com',
    iosClientId: '127539482679-hvulu3ojririvg8j33o8ivc1r12ukmvn.apps.googleusercontent.com',
    iosBundleId: 'com.example.mwntalassessment',
  );
}
